import { guard } from './auth-guard.js';
import { db, functions } from './firebase.js';
import { collection, query, where, orderBy, documentId, startAfter, limit, getDocsFromServer } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-firestore.js';
import { httpsCallable } from 'https://www.gstatic.com/firebasejs/12.0.0/firebase-functions.js';
import { element, message } from './ui.js';
const form=document.querySelector('#student-form'),rows=document.querySelector('#student-rows');
let courses=[],cursor=null,students=[],sessionValid=()=>false,loading=false;
const more=document.querySelector('#load-more');
function resetEditor(){form.reset();form.elements.uid.value='';form.elements.password.required=true;document.querySelector('#initial-password').hidden=false;document.querySelector('#editor-title').textContent='新增學生';}
function edit(student){resetEditor();for(const name of ['uid','name','studentId','className','email']) form.elements[name].value=student[name] || '';form.elements.active.checked=student.active;form.querySelectorAll('[name=courses]').forEach(input=>input.checked=student.courses.includes(input.value));form.elements.password.required=false;document.querySelector('#initial-password').hidden=true;document.querySelector('#editor-title').textContent='編輯學生';form.scrollIntoView({behavior:'smooth'});}
async function invoke(name,data){const result=await httpsCallable(functions,name)(data);return result.data;}
function render(){rows.replaceChildren();rows.hidden=false;for(const student of students){const row=element('tr');for(const value of [student.name,student.studentId,student.className,student.email,student.active?'啟用':'停用',student.courses.map(id=>courses.find(c=>c.id===id)?.title || id).join('、')]) row.append(element('td',value));const actions=element('td');
const editButton=element('button','編輯','button ghost');editButton.onclick=()=>edit(student);
const toggle=element('button',student.active?'停用':'啟用','button ghost');toggle.onclick=async()=>{toggle.disabled=true;try{await invoke('updateStudent',{uid:student.uid,name:student.name,studentId:student.studentId,className:student.className,email:student.email,courses:student.courses,active:!student.active});await loadStudents(true);message('帳號狀態已更新。');}catch{message('更新未完成，請重新載入檢查帳號狀態。');}finally{toggle.disabled=false;}};
const reset=element('button','重設登入權限','button ghost');reset.onclick=async()=>{reset.disabled=true;try{const result=await invoke('resetStudentAccess',{uid:student.uid});if(!sessionValid())return;message('密碼重設連結已產生，請私下交給該學生：'+result.resetLink);}catch{message('重設失敗，請重新載入確認帳號狀態。');}finally{reset.disabled=false;}};
actions.append(editButton,toggle,reset);row.append(actions);rows.append(row);}}
async function loadStudents(fresh=false){if(loading)return;loading=true;try{if(fresh){cursor=null;students=[];}const filters=[where('role','==','student'),orderBy(documentId()),limit(50)];if(cursor)filters.push(startAfter(cursor));const result=await getDocsFromServer(query(collection(db,'users'),...filters));if(!sessionValid())return;students.push(...result.docs.map(doc=>({...doc.data(),uid:doc.id})));cursor=result.docs.at(-1);more.hidden=result.size<50;render();}finally{loading=false;}}
guard({teacher:true,onReady:async(state,valid)=>{sessionValid=valid;const result=await getDocsFromServer(collection(db,'courses'));if(!valid())return;courses=result.docs.map(doc=>({...doc.data(),id:doc.id}));const options=document.querySelector('#course-options');options.replaceChildren();for(const course of courses){const label=element('label',undefined,'check-field'),input=element('input');input.type='checkbox';input.name='courses';input.value=course.id;label.append(input,element('span',course.title));options.append(label);}document.querySelector('#admin-controls').hidden=false;resetEditor();await loadStudents(true);}});
form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;const data={};for(const key of ['name','studentId','className','email'])data[key]=form.elements[key].value.trim();data.active=form.elements.active.checked;data.courses=[...form.querySelectorAll('[name=courses]:checked')].map(input=>input.value);const uid=form.elements.uid.value;if(uid)data.uid=uid;else{data.password=form.elements.password.value;data.requestId=crypto.randomUUID();}try{await invoke(uid?'updateStudent':'createStudent',data);if(!sessionValid())return;resetEditor();await loadStudents(true);message('學生資料已儲存。');}catch{message('儲存未完成，請確認資料及 Email，並重新載入檢查帳號狀態。');}finally{delete data.password;form.elements.password.value='';button.disabled=false;}});
document.querySelector('#cancel-edit').onclick=resetEditor;more.onclick=()=>loadStudents().catch(()=>message('無法載入学生資料。'));
window.addEventListener('private-content-cleared',()=>{document.querySelector('#admin-controls').hidden=true;form.reset();students=[];message('');});

