import { before,test } from 'node:test';import assert from 'node:assert/strict';import { randomUUID, randomBytes } from 'node:crypto';
import { initializeApp,getAuth,getFirestore } from '../functions/admin-sdk.js';
let token,studentToken;const testPassword=randomBytes(18).toString('base64url');
const project='demo-teaching-auth',api='http://127.0.0.1:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=emulator-only';
before(async()=>{if(!process.env.FIREBASE_AUTH_EMULATOR_HOST||!process.env.FIRESTORE_EMULATOR_HOST)throw new Error('Emulators required');initializeApp({projectId:project});const db=getFirestore(),auth=getAuth();for(const [uid,email,role]of[['teacher','teacher@example.test','teacher'],['student-test','student@example.test','student']]){await auth.deleteUser(uid).catch(()=>{});await auth.createUser({uid,email,password:testPassword});await db.doc('users/'+uid).set({role,active:true,name:uid,courses:[],authValidAfter:0});const response=await fetch(api,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:testPassword,returnSecureToken:true})});const data=await response.json();if(uid==='teacher')token=data.idToken;else studentToken=data.idToken;}await db.doc('courses/digital-logic').set({active:true,title:'數位邏輯'});});
async function call(name,data,bearer=token){const response=await fetch('http://127.0.0.1:5001/'+project+'/asia-east1/'+name,{method:'POST',headers:{'Content-Type':'application/json',...(bearer?{Authorization:'Bearer '+bearer}:{})},body:JSON.stringify({data})});return response.json();}
const input=()=>({name:'測試學生',studentId:'20301',className:'二年三班',email:randomUUID()+'@example.test',password:testPassword,courses:['digital-logic'],active:true,requestId:randomUUID()});
test('Anonymous and student cannot invoke management',async()=>{assert((await call('createStudent',input(),null)).error);assert((await call('createStudent',input(),studentToken)).error);});
test('Teacher creates student; profile has no password; duplicate request is rejected',async()=>{const data=input(),result=await call('createStudent',data);assert(result.result?.uid,JSON.stringify(result));const profile=(await getFirestore().doc('users/'+result.result.uid).get()).data();assert.equal(profile.role,'student');assert.equal(profile.active,true);assert(!('password' in profile));assert((await call('createStudent',data)).error);});
test('Role escalation and managing a teacher are rejected',async()=>{assert((await call('createStudent',{...input(),role:'teacher'})).error);const data=input();delete data.password;delete data.requestId;assert((await call('updateStudent',{...data,uid:'teacher'})).error);});
test('Teacher grants, disables and enables a student through backend',async()=>{const data=input(),created=await call('createStudent',data),uid=created.result.uid;delete data.password;delete data.requestId;const disabled=await call('updateStudent',{...data,uid,active:false,courses:[]});assert(disabled.result?.uid,JSON.stringify(disabled));assert.equal((await getAuth().getUser(uid)).disabled,true);assert.equal((await getFirestore().doc('users/'+uid).get()).data().active,false);const enabled=await call('updateStudent',{...data,uid,active:true,courses:['digital-logic']});assert(enabled.result?.uid,JSON.stringify(enabled));assert.equal((await getAuth().getUser(uid)).disabled,false);assert.deepEqual((await getFirestore().doc('users/'+uid).get()).data().courses,['digital-logic']);const reset=await call('resetStudentAccess',{uid});assert(reset.result?.resetLink,JSON.stringify(reset));});

