import { before,after,test } from 'node:test';import fs from 'node:fs';
import { initializeTestEnvironment,assertFails,assertSucceeds } from '@firebase/rules-unit-testing';
import { doc,setDoc,getDoc,updateDoc,collection,getDocs,query,where } from 'firebase/firestore';
import { ref,uploadBytes,getBytes,listAll } from 'firebase/storage';
let env;const token={auth_time:100};
const resource=(courseId,visibility='student',active=true)=>({courseId,chapterId:'chapter01',visibility,active,type:'pdf',storagePath:'protected/'+courseId+'/'+courseId+'-'+visibility+'/lesson.pdf'});
before(async()=>{
 env=await initializeTestEnvironment({projectId:'demo-teaching-auth',firestore:{rules:fs.readFileSync('firestore.rules','utf8')},storage:{rules:fs.readFileSync('storage.rules','utf8')}});
 await env.clearFirestore();await env.clearStorage();
 await env.withSecurityRulesDisabled(async ctx=>{
  for(const [uid,role,active,courses] of [['teacher','teacher',true,[]],['student-a','student',true,['digital-logic']],['student-b','student',true,['digital-logic','electronics-2']],['disabled','student',false,['digital-logic']],['disabled-teacher','teacher',false,[]]])await setDoc(doc(ctx.firestore(),'users',uid),{uid,name:uid,role,active,courses,authValidAfter:0});
  for(const courseId of ['digital-logic','electronics-2']){
   await setDoc(doc(ctx.firestore(),'courses',courseId),{active:true,title:courseId});
   for(const visibility of ['student','teacher']){const data=resource(courseId,visibility);await setDoc(doc(ctx.firestore(),'resources',courseId+'-'+visibility),data);await uploadBytes(ref(ctx.storage(),data.storagePath),new Uint8Array([1,2,3]));}
  }
 });
});
after(async()=>{await env?.cleanup();});
const ctx=uid=>uid?env.authenticatedContext(uid,token):env.unauthenticatedContext();
test('1 Anonymous direct lesson metadata is rejected',async()=>{await assertFails(getDoc(doc(ctx().firestore(),'resources','digital-logic-student')));});
test('2 Anonymous direct PDF and listing are rejected',async()=>{await assertFails(getBytes(ref(ctx().storage(),resource('digital-logic').storagePath)));await assertFails(listAll(ref(ctx().storage(),'protected')));});
test('3 Student A cannot fetch electronics metadata or PDF; Student B can',async()=>{await assertFails(getDoc(doc(ctx('student-a').firestore(),'resources','electronics-2-student')));await assertFails(getBytes(ref(ctx('student-a').storage(),resource('electronics-2').storagePath)));await assertSucceeds(getDoc(doc(ctx('student-b').firestore(),'resources','electronics-2-student')));await assertSucceeds(getBytes(ref(ctx('student-b').storage(),resource('electronics-2').storagePath)));});
test('4 A tampered client still cannot read teacher-only resource',async()=>{await assertFails(getDoc(doc(ctx('student-a').firestore(),'resources','digital-logic-teacher')));await assertFails(getBytes(ref(ctx('student-a').storage(),resource('digital-logic','teacher').storagePath)));});
test('5 Student can get own profile but cannot get another or list students',async()=>{await assertSucceeds(getDoc(doc(ctx('student-a').firestore(),'users','student-a')));await assertFails(getDoc(doc(ctx('student-a').firestore(),'users','student-b')));await assertFails(getDocs(collection(ctx('student-a').firestore(),'users')));});
test('6 Student cannot mutate role, status, courses or create a teacher',async()=>{for(const fields of [{role:'teacher'},{active:true},{courses:['electronics-2']}])await assertFails(updateDoc(doc(ctx('student-a').firestore(),'users','student-a'),fields));await assertFails(setDoc(doc(ctx('student-a').firestore(),'users','invented'),{role:'teacher',active:true}));});
test('7 Disabled users and teachers cannot access resources',async()=>{for(const uid of ['disabled','disabled-teacher']){await assertFails(getDoc(doc(ctx(uid).firestore(),'resources','digital-logic-student')));await assertFails(getBytes(ref(ctx(uid).storage(),resource('digital-logic').storagePath)));}await assertSucceeds(getDoc(doc(ctx('disabled').firestore(),'users','disabled')));});
test('8 Teacher can read users and both content versions, but browser writes remain blocked',async()=>{await assertSucceeds(getDocs(collection(ctx('teacher').firestore(),'users')));await assertSucceeds(getDoc(doc(ctx('teacher').firestore(),'resources','electronics-2-teacher')));await assertSucceeds(getBytes(ref(ctx('teacher').storage(),resource('electronics-2','teacher').storagePath)));await assertFails(updateDoc(doc(ctx('teacher').firestore(),'users','student-a'),{role:'teacher'}));});
test('Storage denies wrong-path/resource mismatch and all browser uploads',async()=>{await assertFails(getBytes(ref(ctx('student-a').storage(),'protected/digital-logic/electronics-2-student/lesson.pdf')));await assertFails(uploadBytes(ref(ctx('teacher').storage(),resource('digital-logic').storagePath),new Uint8Array([4])));});
test('Dynamic permission removal blocks existing sessions without client guard',async()=>{await assertSucceeds(getBytes(ref(ctx('student-a').storage(),resource('digital-logic').storagePath)));await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'users','student-a'),{courses:[]}));await assertFails(getBytes(ref(ctx('student-a').storage(),resource('digital-logic').storagePath)));await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'users','student-a'),{courses:['digital-logic']}));});
test('Revoked auth_time blocks old tokens for reads',async()=>{await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'users','student-a'),{authValidAfter:101}));await assertFails(getDoc(doc(ctx('student-a').firestore(),'resources','digital-logic-student')));await assertFails(getBytes(ref(ctx('student-a').storage(),resource('digital-logic').storagePath)));const renewed=env.authenticatedContext('student-a',{auth_time:102});await assertSucceeds(getBytes(ref(renewed.storage(),resource('digital-logic').storagePath)));await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'users','student-a'),{authValidAfter:0}));});
test('Inactive resource blocks direct bytes and missing user profile is denied',async()=>{await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'resources','digital-logic-student'),{active:false}));await assertFails(getBytes(ref(ctx('student-a').storage(),resource('digital-logic').storagePath)));await assertFails(getDoc(doc(ctx('unknown').firestore(),'resources','electronics-2-student')));await env.withSecurityRulesDisabled(async c=>updateDoc(doc(c.firestore(),'resources','digital-logic-student'),{active:true}));});
test('Student resource queries enforce course and visibility constraints',async()=>{await assertSucceeds(getDocs(query(collection(ctx('student-a').firestore(),'resources'),where('courseId','==','digital-logic'),where('visibility','==','student'),where('active','==',true))));await assertFails(getDocs(collection(ctx('student-a').firestore(),'resources')));});

