import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import { fileURLToPath } from 'node:url';import { load } from 'cheerio';
import { isTeacher,canAccessCourse,canAccessResource,safeCoursePath } from '../js/permissions.js';
import { validateStudent,validateUid } from '../functions/validation.js';
import { buildSite } from '../scripts/build-site.mjs';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url))),manifest=JSON.parse(fs.readFileSync(path.join(root,'data/resource-manifest.json')));
const student={role:'student',active:true,courses:['digital-logic']},teacher={role:'teacher',active:true};
test('Course and visibility boundaries, including disabled teacher',()=>{assert(canAccessCourse(student,'digital-logic'));assert(!canAccessCourse(student,'electronics-2'));assert(!isTeacher(student));assert(canAccessResource(teacher,{courseId:'electronics-2',visibility:'teacher',active:true}));assert(!canAccessResource(student,{courseId:'digital-logic',visibility:'teacher',active:true}));assert(!canAccessResource({...teacher,active:false},{courseId:'digital-logic',visibility:'student',active:true}));assert(!canAccessResource(student,{courseId:'digital-logic',visibility:'student',active:false}));assert.throws(()=>safeCoursePath('../admin'));});
test('Backend validates inputs and rejects role escalation payload',()=>{const valid={name:'王小明',studentId:'20301',className:'二年三班',email:'STUDENT@example.test',courses:['digital-logic'],active:true,password:'a-long-test-value'};assert.equal(validateStudent(valid,['digital-logic'],true).email,'student@example.test');assert.throws(()=>validateStudent({...valid,role:'teacher'},['digital-logic'],true));assert.throws(()=>validateStudent({...valid,courses:['unknown']},['digital-logic'],true));assert.throws(()=>validateStudent({...valid,password:'short'},['digital-logic'],true));assert.throws(()=>validateUid('../teacher'));});
test('All 21 lesson and quiz URLs contain only shells',()=>{const html=manifest.resources.filter(x=>['lesson','quiz'].includes(x.type));assert.equal(html.length,21);for(const resource of html){const text=fs.readFileSync(path.join(root,resource.originalPath),'utf8'),$=load(text);assert.equal($('#lesson-content').attr('data-resource-id'),resource.id);assert.equal($('main .lesson, main details, main .q, main img').length,0);assert(!text.includes('答案：'));assert(!text.includes('downloads/digital-logic/'));}});
test('Public build excludes all protected bytes and backend/migration files',()=>{buildSite();const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);const files=walk(path.join(root,'site'));assert(files.every(p=>!p.endsWith('.pdf')&&!p.endsWith('.png')));assert(!fs.existsSync(path.join(root,'site/functions')));assert(!fs.existsSync(path.join(root,'site/migration-private')));assert(fs.existsSync(path.join(root,'site/dashboard/index.html')));assert(fs.existsSync(path.join(root,'site/admin/index.html')));for(const resource of manifest.resources.filter(x=>!['lesson','quiz'].includes(x.type)))assert(!fs.existsSync(path.join(root,resource.originalPath)));});
test('No password storage or permanent download API in frontend',()=>{const scripts=fs.readdirSync(path.join(root,'js')).filter(x=>x.endsWith('.js')).map(x=>fs.readFileSync(path.join(root,'js',x),'utf8')).join(String.fromCharCode(10));assert(!scripts.includes('getDownloadURL'));assert(!scripts.includes('createUserWithEmailAndPassword'));assert(!scripts.includes('firebase-admin'));assert(!/localStorage\.setItem/.test(scripts));assert(scripts.includes('getBlob'));});
test('Public links resolve to existing pages; former PDF links use resource gate',()=>{const walk=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(p,e.name)):[path.join(p,e.name)]);for(const file of walk(path.join(root,'site')).filter(x=>x.endsWith('.html'))){const $=load(fs.readFileSync(file,'utf8'));for(const el of $('a[href],script[src],link[href]').toArray()){const href=$(el).attr('href')||$(el).attr('src');if(!href||/^(https?:|#|mailto:)/.test(href))continue;const p=path.resolve(path.dirname(file),href.split(/[?#]/)[0]);assert(fs.existsSync(p),path.relative(root,file)+' -> '+href);}}});


test('Resource IDs and Storage paths are unique',()=>{assert.equal(new Set(manifest.resources.map(x=>x.id)).size,manifest.resources.length);assert.equal(new Set(manifest.resources.map(x=>x.storagePath)).size,manifest.resources.length);});
